# -*- coding: utf-8 -*-
"""Pesapal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OOJCdBGKlS9b4qJsn2cZDxxnrmXdzdIx
"""

import streamlit as st
import pandas as pd
from io import StringIO
from datetime import datetime

st.title("Pesapal to QuickBooks IIF Converter (Receivables Mode)")

uploaded_file = st.file_uploader("Upload Pesapal CSV file", type=["csv"])

if uploaded_file:
    df = pd.read_csv(uploaded_file)
    df = df[df['Payment Method'].isin(['CREDITCARDMC_CYB_KE', 'VOUCHER'])]

    iif = StringIO()
    iif.write("!TRNS\tTRNSTYPE\tDATE\tACCNT\tNAME\tAMOUNT\tMEMO\n")
    iif.write("!SPL\tTRNSTYPE\tDATE\tACCNT\tNAME\tAMOUNT\tMEMO\n")
    iif.write("!ENDTRNS\n")

    for idx, row in df.iterrows():
        date_str = pd.to_datetime(row['Date']).strftime('%m/%d/%Y')
        memo = f"{row.get('Buyer Name', '')} | {row.get('Description', '')}"
        net_amount = round(row.get("Net Amount", 0), 2)
        commission = round(row.get("Commission", 0), 2)
        name = row.get("Buyer Name") or "Customer"

        if row['Payment Method'] == 'CREDITCARDMC_CYB_KE':
            # Customer payment received
            iif.write(f"TRNS\tPAYMENT\t{date_str}\tAccounts Receivable\t{name}\t{-net_amount}\t{memo}\n")
            iif.write(f"SPL\tPAYMENT\t{date_str}\tPesapal\t{name}\t{net_amount}\t{memo}\n")
            iif.write("ENDTRNS\n")

            if commission > 0:
                # Bank service charge
                iif.write(f"TRNS\tCHECK\t{date_str}\tPesapal\t{-commission}\tPesapal Transaction Fee\n")
                iif.write(f"SPL\tCHECK\t{date_str}\tBank Service Charges\t\t{commission}\tPesapal commission\n")
                iif.write("ENDTRNS\n")

        elif row['Payment Method'] == 'VOUCHER':
            # Loan repayment
            iif.write(f"TRNS\tCHECK\t{date_str}\tPesapal\t{-net_amount}\tPesapal Loan Auto Repayment\n")
            iif.write(f"SPL\tCHECK\t{date_str}\tLoan:Pesapal Loan\t\t{net_amount}\tPesapal Loan Auto Repayment\n")
            iif.write("ENDTRNS\n")

    st.download_button(
        label="Download IIF File",
        data=iif.getvalue(),
        file_name="pesapal_receivables_import.iif",
        mime="text/plain"
    )

    st.success("IIF file generated using 'PAYMENT to Receivables' method.")
